"""empty message

Revision ID: 14c74e74a66
Revises: 31cb2156bf9
Create Date: 2016-01-27 20:32:39.418018

"""

# revision identifiers, used by Alembic.
revision = '14c74e74a66'
down_revision = '31cb2156bf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
