"""empty message

Revision ID: 1ce610df5d9
Revises: 5ae62fd7980
Create Date: 2015-11-26 15:11:49.917132

"""

# revision identifiers, used by Alembic.
revision = '1ce610df5d9'
down_revision = '5ae62fd7980'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
