"""empty message

Revision ID: 31cb2156bf9
Revises: 1b0f9331e71
Create Date: 2016-01-26 21:38:13.801693

"""

# revision identifiers, used by Alembic.
revision = '31cb2156bf9'
down_revision = '1b0f9331e71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('url', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('careers', 'url')
    ### end Alembic commands ###
