"""empty message

Revision ID: 48f3a669a2b
Revises: None
Create Date: 2015-11-20 18:40:20.660364

"""

# revision identifiers, used by Alembic.
revision = '48f3a669a2b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
