"""empty message

Revision ID: 4ce9ed70807
Revises: 48f3a669a2b
Create Date: 2015-11-22 19:29:12.034491

"""

# revision identifiers, used by Alembic.
revision = '4ce9ed70807'
down_revision = '48f3a669a2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
