"""empty message

Revision ID: 538ac8ae759
Revises: 14c74e74a66
Create Date: 2016-01-27 21:03:19.527845

"""

# revision identifiers, used by Alembic.
revision = '538ac8ae759'
down_revision = '14c74e74a66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('def_avatar', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'def_avatar')
    ### end Alembic commands ###
